Repository GDSCUTM-CommunityProjects/ActNow, pull requests merged in 2021-11, with the labels that each got.

#98 Feat/overhauled server
  src/platform/api (legacy)/package-lock.json
  src/platform/api (legacy)/test_new.js
  src/platform/functions/index.js
  src/platform/functions/package-lock.json
  src/platform/functions/package.json
Labels: enhancement, Platform

#99 Share User Location
  src/app/assets/Icon.png
  src/app/lib/home_page.dart
  src/app/lib/pages/explore_page.dart
  src/app/lib/pages/map_page/map_page.dart
  src/app/lib/pages/profile_page/profile_page.dart
  src/app/lib/signup_screen.dart
  src/app/pubspec.yaml
Labels: Application

#101 Feat/location parameter scraper 2
  src/platform/functions/index.js
Labels: enhancement, Platform

#108 Created deleteOutdatedUserEvents cloud function
  src/platform/functions/.eslintrc.json
  src/platform/functions/index.js
Labels: Platform

#103 Edit user profile picture
  src/app/lib/pages/profile_page/personal_info.dart
Labels: Application

#107 Add explore page search bar
  src/app/lib/pages/explore_page.dart
  src/app/lib/widgets/event_widget.dart
  src/app/lib/widgets/search_widget.dart
Labels: Application

#112 Saved events
  src/app/lib/pages/explore_page.dart
  src/app/lib/signup_screen.dart
  src/app/lib/widgets/event_widget.dart
Labels: Application

#111 Feat/display scraped
  src/app/android/app/src/main/AndroidManifest.xml
  src/app/lib/pages/event_details.dart
  src/app/lib/pages/explore_page.dart
  src/app/lib/pages/map_page/map_page.dart
  src/app/lib/widgets/event_widget.dart
  src/app/pubspec.lock
  src/app/pubspec.yaml
  src/platform/functions/index.js
  src/platform/functions/package-lock.json
  src/platform/functions/package.json
Labels: Application, Platform

#114 Docs - add docs for platform
  src/documentation/docs/Platform/breakdown.md
  src/documentation/docs/Platform/functions.md
  src/documentation/package-lock.json
  src/documentation/package.json
  src/platform/functions/index.js
Labels: documentation

#115 Feat/rescrape events
  src/platform/functions/.eslintrc.json
  src/platform/functions/index.js
Labels: enhancement

#116 Platform - fixing scraper
  src/platform/functions/index.js
Labels: bug

#117 Platform - fixed city case
  src/platform/functions/index.js
Labels: bug

#118 Platform - fix event data structure
  src/platform/functions/.eslintrc.json
  src/platform/functions/index.js
Labels: bug

#119 Call Scraper on empty cities.
  src/app/android/app/src/main/AndroidManifest.xml
  src/app/lib/pages/explore_page.dart
  src/app/lib/pages/map_page/add_event.dart
  src/app/lib/pages/map_page/map_page.dart
  src/platform/functions/index.js
Labels: Application

#120 Application - added some docs
  src/documentation/docs/Application/usage.md
  src/documentation/static/img/email-signup.png
  src/documentation/static/img/explore.png
  src/documentation/static/img/google-signup.png
  src/documentation/static/img/maps.png
  src/documentation/static/img/profile.png
  src/documentation/static/img/saved.png
Labels: documentation

#121 Feat/event details bug
  src/platform/functions/index.js
Labels: bug

#122 Feat/saved events page
  src/app/lib/home_page.dart
  src/app/lib/pages/explore_page.dart
  src/app/lib/pages/saved_page.dart
Labels: Application

#124 Bug/event img fix
  src/platform/functions/index.js
Labels: Platform
