Repository GDSCUTM-CommunityProjects/ActNow, pull requests merged in 2021-09, with the labels that each got.

#22 Docs - Added documentation to our project
  src/documentation/.gitignore
  src/documentation/README.md
  src/documentation/babel.config.js
  src/documentation/build/.nojekyll
  src/documentation/build/404.html
  src/documentation/build/assets/css/styles.3a2db4c5.css
  src/documentation/build/assets/js/0e384e19.ad1e2a11.js
  src/documentation/build/assets/js/17896441.4358cb3e.js
  src/documentation/build/assets/js/1be78505.0e723370.js
  src/documentation/build/assets/js/1f391b9e.5ce2d2c3.js
  src/documentation/build/assets/js/3720c009.3879c85f.js
  src/documentation/build/assets/js/393be207.b2a6eb20.js
  src/documentation/build/assets/js/55960ee5.efcf260c.js
  src/documentation/build/assets/js/63a4c193.9c19e460.js
  src/documentation/build/assets/js/75.37c134a7.js
  src/documentation/build/assets/js/845.e72604d5.js
  src/documentation/build/assets/js/935f2afb.7499acc0.js
  src/documentation/build/assets/js/9dd8a0d2.97d8835f.js
  src/documentation/build/assets/js/9e4087bc.9e2b5cf6.js
  src/documentation/build/assets/js/a6a1651e.b867d551.js
  src/documentation/build/assets/js/b2f554cd.e00e7964.js
  src/documentation/build/assets/js/common.f639990b.js
  src/documentation/build/assets/js/common.f639990b.js.LICENSE.txt
  src/documentation/build/assets/js/main.c5c5b111.js
  src/documentation/build/assets/js/main.c5c5b111.js.LICENSE.txt
  src/documentation/build/assets/js/runtime~main.48b58d6a.js
  src/documentation/build/blog/archive/index.html
  src/documentation/build/docs/Application/intro/index.html
  src/documentation/build/docs/Platform/intro/index.html
  src/documentation/build/docs/intro/index.html
  src/documentation/build/docs/tags/index.html
  src/documentation/build/img/docusaurus.png
  src/documentation/build/img/easy.svg
  src/documentation/build/img/favicon.ico
  src/documentation/build/img/focus.svg
  src/documentation/build/img/logo.svg
  src/documentation/build/img/phone.svg
  src/documentation/build/index.html
  src/documentation/build/markdown-page/index.html
  src/documentation/build/sitemap.xml
  src/documentation/docs/Application/intro.mdx
  src/documentation/docs/Platform/intro.mdx
  src/documentation/docs/intro.md
  src/documentation/docusaurus.config.js
  src/documentation/package-lock.json
  src/documentation/package.json
  src/documentation/sidebars.js
  src/documentation/src/components/HomepageFeatures.js
  src/documentation/src/components/HomepageFeatures.module.css
  src/documentation/src/css/custom.css
  src/documentation/src/pages/index.jsx
  src/documentation/src/pages/index.module.css
  src/documentation/src/pages/markdown-page.md
  src/documentation/static/.nojekyll
  src/documentation/static/img/docusaurus.png
  src/documentation/static/img/easy.svg
  src/documentation/static/img/favicon.ico
  src/documentation/static/img/focus.svg
  src/documentation/static/img/logo.svg
  src/documentation/static/img/phone.svg
Labels: enhancement

#24 User Login Feature - Email/Pass
  src/app/lib/decisions_tree.dart
  src/app/lib/home_page.dart
  src/app/lib/login_screen.dart
  src/app/lib/main.dart
  src/app/lib/signup_screen.dart
Labels: enhancement

#26 Firebase - fixed ios issue
  src/app/android/.gitignore
  src/app/android/app/google-services.json
  src/app/ios/.gitignore
  src/app/ios/Flutter/Debug.xcconfig
  src/app/ios/Flutter/Release.xcconfig
  src/app/ios/Podfile
  src/app/ios/Podfile.lock
  src/app/ios/Runner.xcodeproj/project.pbxproj
  src/app/ios/Runner.xcworkspace/contents.xcworkspacedata
  src/app/ios/Runner/GoogleService-Info.plist
  src/app/ios/Runner/Info.plist
Labels: bug

#32 Docs - added intro docs
  src/documentation/.gitignore
  src/documentation/build/.nojekyll
  src/documentation/build/404.html
  src/documentation/build/assets/css/styles.3a2db4c5.css
  src/documentation/build/assets/js/0e384e19.ad1e2a11.js
  src/documentation/build/assets/js/17896441.4358cb3e.js
  src/documentation/build/assets/js/1be78505.0e723370.js
  src/documentation/build/assets/js/1f391b9e.5ce2d2c3.js
  src/documentation/build/assets/js/3720c009.3879c85f.js
  src/documentation/build/assets/js/393be207.b2a6eb20.js
  src/documentation/build/assets/js/55960ee5.efcf260c.js
  src/documentation/build/assets/js/63a4c193.9c19e460.js
  src/documentation/build/assets/js/75.37c134a7.js
  src/documentation/build/assets/js/845.e72604d5.js
  src/documentation/build/assets/js/935f2afb.7499acc0.js
  src/documentation/build/assets/js/9dd8a0d2.97d8835f.js
  src/documentation/build/assets/js/9e4087bc.9e2b5cf6.js
  src/documentation/build/assets/js/a6a1651e.b867d551.js
  src/documentation/build/assets/js/b2f554cd.e00e7964.js
  src/documentation/build/assets/js/common.f639990b.js
  src/documentation/build/assets/js/common.f639990b.js.LICENSE.txt
  src/documentation/build/assets/js/main.c5c5b111.js
  src/documentation/build/assets/js/main.c5c5b111.js.LICENSE.txt
  src/documentation/build/assets/js/runtime~main.48b58d6a.js
  src/documentation/build/blog/archive/index.html
  src/documentation/build/docs/Application/intro/index.html
  src/documentation/build/docs/Platform/intro/index.html
  src/documentation/build/docs/intro/index.html
  src/documentation/build/docs/tags/index.html
  src/documentation/build/img/docusaurus.png
  src/documentation/build/img/easy.svg
  src/documentation/build/img/favicon.ico
  src/documentation/build/img/focus.svg
  src/documentation/build/img/logo.svg
  src/documentation/build/img/phone.svg
  src/documentation/build/index.html
  src/documentation/build/markdown-page/index.html
  src/documentation/build/sitemap.xml
  src/documentation/docs/Application/index.md
  src/documentation/docs/General/_category_.json
  src/documentation/docs/General/how_to_contribute.md
  src/documentation/docs/Platform/index.md
  src/documentation/docs/index.md
  src/documentation/docs/intro.md
  src/documentation/docusaurus.config.js
  src/documentation/src/components/HomepageFeatures.js
  src/documentation/src/pages/index.jsx
  src/documentation/static/img/netlify-check.png
Labels: documentation

#28 User Registration Feature
  src/app/lib/login_screen.dart
  src/app/lib/signup_screen.dart
Labels: enhancement

#36 Flutter - added ci
  .github/worflows/app_ci.yml
  src/app/test/widget_test.dart
Labels: enhancement

#42 Added the intro docs for the application team
  src/documentation/docs/Application/index.md
Labels: documentation

#34 Feat/event server
  src/api/.eslintrc.json
  src/api/.gitignore
  src/api/babel.config.json
  src/api/index.js
  src/api/package-lock.json
  src/api/package.json
Labels: enhancement
