Repository GDSCUTM-CommunityProjects/ActNow, pull requests merged in 2021-12, with the labels that each got.

#127 display map before scraped events are loaded
  src/app/lib/pages/map_page/map_page.dart
Labels: Application

#137 Platform - added husky
  .gitignore
  .husky/pre-push
  package-lock.json
  package.json
Labels: Platform

#138 Application - updated profile page
  src/app/lib/pages/profile_page/profile_page.dart
Labels: Application

#139 Contact us feature
  src/app/lib/pages/event_details.dart
  src/app/lib/pages/profile_page/contact_us.dart
  src/app/pubspec.lock
  src/app/pubspec.yaml
Labels: Application

#143 Platform - added geocoding to scraper
  src/platform/functions/.gitignore
  src/platform/functions/index.js
  src/platform/functions/package-lock.json
  src/platform/functions/package.json
Labels: enhancement, Platform

#145 Documentation - added docs on cloud scheduler interaction
  src/documentation/docs/Platform/cloudscheduler.md
  src/documentation/static/img/cloud-scheduler.png
Labels: documentation

#141 added function flow for periodicScraperFunction
  src/documentation/docs/Platform/api-legacy.md
  src/documentation/docs/Platform/breakdown.md
  src/documentation/docs/Platform/functions.md
Labels: documentation

#144 remove geocoding from application side
  src/app/lib/pages/event_details.dart
  src/app/lib/pages/map_page/map_page.dart
Labels: Application

#146 Testing - added tests for explore page
  src/app/lib/pages/explore_page.dart
  src/app/pubspec.lock
  src/app/pubspec.yaml
  src/app/test/explore_page_test.dart
  src/app/test/mock_image_http.dart
  src/app/test/mock_network_image.dart
Labels: enhancement, Platform

#147 Testing - Added search widget tests
  src/app/test/search_widget_test.dart
Labels: Application

#148 Test - added tests for event_widget
  src/app/test/event_widget_test.dart
Labels: Application
