Repository GDSCUTM-CommunityProjects/ActNow, pull requests merged in 2021-10, with the labels that each got.

#53 Final Designs implmentation
  src/app/android/app/src/main/AndroidManifest.xml
  src/app/assets/Logo.png
  src/app/fonts/OFL.txt
  src/app/fonts/PTSans-Bold.ttf
  src/app/fonts/PTSans-BoldItalic.ttf
  src/app/fonts/PTSans-Italic.ttf
  src/app/fonts/PTSans-Regular.ttf
  src/app/ios/Podfile
  src/app/ios/Podfile.lock
  src/app/ios/Runner/Info.plist
  src/app/lib/home_page.dart
  src/app/lib/login_screen.dart
  src/app/lib/main.dart
  src/app/lib/pages/explore_page.dart
  src/app/lib/pages/map_page.dart
  src/app/lib/pages/profile_page.dart
  src/app/lib/pages/saved_page.dart
  src/app/lib/signup_screen.dart
  src/app/pubspec.lock
  src/app/pubspec.yaml
Labels: Application

#56 Update app_ci.yml Flutter Version
  .github/workflows/app_ci.yml
Labels: bug

#65 Feat/forgot password
  src/app/lib/forgot_password_screen.dart
  src/app/lib/login_screen.dart
  src/app/lib/pages/explore_page.dart
  src/app/pubspec.lock
Labels: enhancement

#67 Feat/basic map
  src/app/android/app/src/main/AndroidManifest.xml
  src/app/ios/Runner/AppDelegate.swift
  src/app/lib/pages/map_page.dart
  src/app/pubspec.lock
  src/app/pubspec.yaml
Labels: enhancement, Application

#71 Maps Page - Add event feature
  src/app/ios/Podfile.lock
  src/app/ios/Runner/Info.plist
  src/app/lib/home_page.dart
  src/app/lib/login_screen.dart
  src/app/lib/pages/map_page/add_event.dart
  src/app/lib/pages/map_page/map_page.dart
  src/app/lib/pages/saved_page.dart
  src/app/pubspec.lock
  src/app/pubspec.yaml
Labels: Application

#83 Improved Location Field
  .github/workflows/app_ci.yml
  .gitignore
  src/app/lib/main.dart
  src/app/lib/pages/explore_page.dart
  src/app/lib/pages/map_page/add_event.dart
  src/app/lib/pages/map_page/map_page.dart
  src/app/pubspec.lock
  src/app/pubspec.yaml
Labels: Application

#88 Application - added event widget
  src/app/ios/Runner.xcodeproj/project.pbxproj
  src/app/lib/login_screen.dart
  src/app/lib/pages/event_widget.dart
  src/app/lib/pages/explore_page.dart
  src/app/pubspec.lock
Labels: enhancement, Application
